### PR TITLE
tests needed for p2p (currently failing)

### PR DESCRIPTION
**Pull request by dominictarr**
test the actual behavior that is needed to implement p2p.
changes: os.networkInterfaces() must tell you the ip, etc

must be able to bind a socket, send a packet, and it must error if the port was already bound

### CODE REVIEW

**Comment by dominictarr** [comment]
Also note, if you comment/uncomment the import line. you can run the tests in node.
Of course, they will pass in node, but you can use this to make sure the tests are actually correct.

hmm, is it possible for @socketsupply/io to just return the node modules when used in node?

**Comment by heapwolf** [comment]
Just making a note that this is a Linux-specific issue, and there is a fix in sdk that needs testing.

**Comment by dominictarr** [comment]
in my opinion we should merge merge this. it's wrong to merge code that breaks tests, but sometimes it's the right move to merge tests that are currently failing.

**Comment by heapwolf** [comment]
CI seems misconfigured, we should fix that. For now this is the results of my manual tests. `MacOS M2 12.4`, `MacOS M1 12.4`, `iOS iPhone 13 15.6` `iOS iPhone 12 15.6`

```
1..145
# tests 145
# pass  145

# ok
```

I'll test Linux/Android with @jwerle

**Pull request merged**
